### ISSUE TITLE
5.5_Record와 Partial을 활용하여 정확한 타입 표현하는 코드를 작성해보세요

### ISSUE THREAD

**Issue by seohag** [team-Palindrome/TypeScript-Study#5]
💥 5.5 Record와 Partial을 활용해서 타입 추론하기(p.179)

개인 프로젝트 혹은 팀 프로젝트에서 사용한 코드를 일부 발췌하여 Record와 Partial을 활용해서 타입을 명시하는 코드를 작성해보세요

해당이 없을시 코드 작성 작성도 가능

**Comment by alswla** [comment]
키가 한정되어 있어 `Partial`은 사용하지 않고 `Record`만 사용하여 ts 로 변경한 코드 제출합니다.

```ts
// krossCutting 프로젝트의 ./src/store/index.js의 store 일부입니다.

type StartPointKeys = "mainStartPoint" | "subOneStartPoint" | "subTwoStartPoint";
type StartPoints = Record<StartPointKeys, number | null>;

interface StartPointStore {
  startPoints: StartPoints;
  setStartPoint: (key: StartPointKeys, value: number | null) => void;
  clearStartPoints: () => void;
}

const useStartPointStore = create<StartPointStore>(devtools((set) => ({
  startPoints: {
    mainStartPoint: null,
    subOneStartPoint: null,
    subTwoStartPoint: null,
  },
  setStartPoint: (key, value) =>
    set((state) => ({
      startPoints: { ...state.startPoints, [key]: value },
    })),
  clearStartPoints: () =>
    set({
      startPoints: {
        mainStartPoint: null,
        subOneStartPoint: null,
        subTwoStartPoint: null,
      },
    }),
})));
```

**Comment by sunghankwon** [comment]
Record와 Partial을 적용하였습니다.

```ts
// its Comments 프로젝트의 ./src/store/useComments.js의 코드 일부를 마이그레이션 한 코드입니다.

interface ReComment {
  text: string;
  creator: string;
  postDate: Date;
}

interface Comment {
  creator: string;
  text: string;
  postDate: Date;
  postUrl: string;
  postCoordinate: {
    x: string;
    y: string;
  };
  screenshot: string;
  allowPublic: boolean;
  publicUsers: string[];
  recipientEmail: string[];
  reComments: ReComment[];
  expiresAt: Date;
}

interface UserComments extends Record<'createdComments' | 'feedComments' | 'receivedComments', Comment[]> {}

interface CommentsState {
  userComments: UserComments;
  setUserComments: (comments: Partial<UserComments>) => void;
}

const useCommentsStore = create<CommentsState>((set) => ({
  userComments: {
    createdComments: [],
    feedComments: [],
    receivedComments: [],
  },
  setUserComments: (comments: Partial<UserComments>) => set({ userComments: { ...useCommentsStore.getState().userComments, ...comments } }),
}));

```
Record를 적용하여 createdComments, feedComments, receivedComments를 각각 카테고리와 하였습니다.
Partial을 적용하여 createdComments, feedComments, receivedComments를 별도로 업데이트 하는 조작이 가능하게 수정하였습니다.

**Comment by alswla** [comment]
**5/12(일) 코드 리뷰 및 스터디 정리** 

**Record** 
> [Record](https://www.typescriptlang.org/docs/handbook/utility-types.html#recordkeys-type) 타입의 경우, 지정된 모든 키를 포함하고, 각 키는 지정된 타입의 값을 가져야 하는 객체 타입을 정의합니다.
> 즉, 유니온으로 지정되었더라도 유니온으로 지정된 모든 키에 대한 값을 가져야 합니다.

<br>

**Partial**
> Partial의 경우 책에 나온 것과 같이 `undefined`를 구별하는 용도로도 쓰일 수 있지만, 무조건 `undefined`를 구별하기 위한 것만은 아닙니다.
>
> [Partial<T>](https://www.typescriptlang.org/docs/handbook/utility-types.html#partialtype)는 제네릭 타입 T의 모든 속성을 선택적으로 만든 새로운 타입을 생성합니다. 이를 통해 T 타입의 모든 속성을 필수가 아닌 선택적으로 만들 수 있습니다.

<br>

**왜 성한님은 Partial을 사용하고 민지님은 사용하지 않았는지**
> **한민지님(@alswla)의 코드**
>
> `useStartPointStore는` 세 개의 특정 키에 대해 각각의 값을 관리합니다.
>
> `setStartPoint` 함수는 개별 키(`StartPointKeys`)와 값을 받아 해당 키에 대한 상태만 업데이트합니다. 상태의 나머지 부분은 변경되지 않습니다. 이 함수는 이미 특정 키에 대한 세밀한 업데이트를 수행할 수 있도록 설계되었습니다.
>
> 따라서 이 구조에서는 각 호출에서 단 하나의 키만 업데이트하므로, 전체 `StartPoints` 객체를 다시 구성할 필요가 없습니다. 따라서 Partial의 사용이 필요 없습니다.
>

> **권성한님(@sunghankwon)의 코드**
>
> `useCommentsStore`는 여러 댓글의 배열(`createdComments, feedComments, receivedComments`)을 관리합니다. 각 배열은 `Comment[]` 타입입니다.
>
> `setUserComments` 함수는 `UserComments` 객체의 부분적인 업데이트를 허용합니다. 즉, 호출할 때 `createdComments`, `feedComments`, `receivedComments` 중 일부 또는 전부를 업데이트할 수 있습니다.
>
> 따라서 함수를 호출할 때 필요한 부분만 명시할 수 있도록 Partial을 사용합니다.

<br>

**추가 질문이 있거나 궁금한 사항 혹은 이해가 되지 않는 부분은 코멘트를 남겨주세요!**
